### ISSUE TITLE
【FE】レシピカード

### ISSUE THREAD

**Issue by ysm0706glee** [qin-team-recipe/11-recipe-app#3]
## ゴール

- [x] 受け取ったレシピを表示する。
- [x] クリックでレシピ詳細に遷移。

## 概要

propsとして受け取ったレシピを表示。
遷移先のURLは仮。

## タスク

- [x] UIを作成
- [x] URL構成が決まり次第遷移先を修正。

**Comment by ysm0706glee** [comment]
![Image](https://github.com/qin-team-recipe/11-recipe-app/assets/74037163/232f9544-37dc-4f87-a7d5-e62b2c2e14ab)

**Comment by Keitoto** [comment]
## ゴール

- [ ] 受け取ったレシピを表示する。
- [ ] クリックでレシピ詳細に遷移。

## 概要

propsとして受け取ったレシピを表示。
遷移先のURLは仮。

## タスク

- [ ] UIを作成
- [ ] Backend実装後Typeに変更があれば修正。
- [ ] URL構成が決まり次第遷移先を修正。
